### ISSUE TITLE
Doc comment

### ISSUE THREAD

**Issue by HK-vv** [HK-vv/SE-BSsystem#8]
see Requirment and API doc. (search "COMMENT" or "TODO" in doc)

- [x] function A2  @TedLee515 

- [x] function A7 and C1 @Palant1r 

- [x] API doc @Edd1eX 

Close this issue after all tasks achieved.

**Comment by Edd1eX** [comment]
Username search already exists, using the 'keyword'

**Comment by HK-vv** [comment]
> Username search already exists, using the 'keyword'

my fault...

**Comment by CasanovaLLL** [comment]
ops I seem to have ticked the task I don't know who.

**Comment by HK-vv** [comment]
> ops I seem to have ticked the task I don't know who.

you know its possible to undo that, right?...
